import { ItemType } from "../component/LaundaryItem/ItemListing";

export const Items = (category: string): ItemType[] => {
  if (category === "wash_and_iron") {
    return [
      {
        id: "1",
        name: "White Abgada",
        qty: 0,
        price: 2000,
        image_url: "./w-abgada.png",
      },
      {
        id: "2",
        name: "Colored Abgada",
        qty: 0,
        price: 1500,
        image_url: "./agbada.png",
      },
      {
        id: "3",
        name: "Suit",
        qty: 0,
        price: 1500,
        image_url: "./suit.png",
      },
      {
        id: "4",
        name: "White Suit",
        qty: 0,
        price: 2000,
        image_url: "./suit.png",
      },
      {
        id: "5",
        name: "Kaftan",
        qty: 0,
        price: 400,
        image_url: "./Kaftan.jpg",
      },
      {
        id: "6",
        name: "White Kaftan",
        qty: 0,
        price: 600,
        image_url: "./w-kaftan.jpg",
      },
      {
        id: "7",
        name: "Shirt",
        qty: 0,
        price: 200,
        image_url: "./shirts.jpg",
      },
      {
        id: "8",
        name: "White Shirt",
        qty: 0,
        price: 300,
        image_url: "./w-shirts.webp",
      },
      {
        id: "9",
        name: "Sweater",
        qty: 0,
        price: 500,
        image_url: "./sweater.jpg",
      },
      {
        id: "10",
        name: "Jacket",
        qty: 0,
        price: 500,
        image_url: "./jacket.webp",
      },
      {
        id: "11",
        name: "White Gown",
        qty: 0,
        price: 500,
        image_url: "./gown.webp",
      },
      {
        id: "12",
        name: "Gown",
        qty: 0,
        price: 600,
        image_url: "./gown.webp",
      },
      {
        id: "13",
        name: "Shirt",
        qty: 0,
        price: 200,
        image_url: "./shirts.jpg",
      },
      {
        id: "14",
        name: "Shirt & Blouse",
        qty: 0,
        price: 400,
        image_url: "./skirt&blouse.jpg",
      },
      {
        id: "15",
        name: "Small Towel",
        qty: 0,
        price: 300,
        image_url: "./towel.jpg",
      },
      {
        id: "16",
        name: "Big Towel",
        qty: 0,
        price: 500,
        image_url: "./towel.jpg",
      },
      {
        id: "17",
        name: "Small Duvet",
        qty: 0,
        price: 1500,
        image_url: "./duviet.webp",
      },
      {
        id: "18",
        name: "Big Duvet",
        qty: 0,
        price: 2000,
        image_url: "./duviet.webp",
      },
    ];
  } else if (category === "wash") {
    return [
      {
        id: "1",
        name: "White Abgada",
        qty: 0,
        price: 1500,
        image_url: "./w-abgada.png",
      },
      {
        id: "2",
        name: "Colored Abgada",
        qty: 0,
        price: 1000,
        image_url: "./agbada.png",
      },
      {
        id: "3",
        name: "Suit",
        qty: 0,
        price: 1000,
        image_url: "./suit.png",
      },
      {
        id: "4",
        name: "White Suit",
        qty: 0,
        price: 1500,
        image_url: "./suit.png",
      },
      {
        id: "5",
        name: "Kaftan",
        qty: 0,
        price: 200,
        image_url: "./Kaftan.jpg",
      },
      {
        id: "6",
        name: "White Kaftan",
        qty: 0,
        price: 400,
        image_url: "./w-kaftan.jpg",
      },
      {
        id: "7",
        name: "Shirt",
        qty: 0,
        price: 100,
        image_url: "./shirts.jpg",
      },
      {
        id: "8",
        name: "White Shirt",
        qty: 0,
        price: 150,
        image_url: "./w-shirts.webp",
      },
      {
        id: "9",
        name: "Sweater",
        qty: 0,
        price: 300,
        image_url: "./sweater.jpg",
      },
      {
        id: "10",
        name: "Jacket",
        qty: 0,
        price: 300,
        image_url: "./jacket.webp",
      },
      {
        id: "11",
        name: "White Gown",
        qty: 0,
        price: 300,
        image_url: "./gown.webp",
      },
      {
        id: "12",
        name: "Gown",
        qty: 0,
        price: 400,
        image_url: "./gown.webp",
      },
      {
        id: "13",
        name: "Shirt",
        qty: 0,
        price: 100,
        image_url: "./shirts.jpg",
      },
      {
        id: "14",
        name: "Shirt & Blouse",
        qty: 0,
        price: 250,
        image_url: "./skirt&blouse.jpg",
      },
      {
        id: "15",
        name: "Small Towel",
        qty: 0,
        price: 300,
        image_url: "./towel.jpg",
      },
      {
        id: "16",
        name: "Big Towel",
        qty: 0,
        price: 500,
        image_url: "./towel.jpg",
      },
      {
        id: "17",
        name: "Small Duvet",
        qty: 0,
        price: 1500,
        image_url: "./duviet.webp",
      },
      {
        id: "18",
        name: "Big Duvet",
        qty: 0,
        price: 2000,
        image_url: "./duviet.webp",
      },
    ];
  } else if (category === "iron") {
    return [
      {
        id: "1",
        name: "White Abgada",
        qty: 0,
        price: 700,
        image_url: "./w-abgada.png",
      },
      {
        id: "2",
        name: "Colored Abgada",
        qty: 0,
        price: 600,
        image_url: "./agbada.png",
      },
      {
        id: "3",
        name: "Suit",
        qty: 0,
        price: 600,
        image_url: "./suit.png",
      },
      {
        id: "4",
        name: "White Suit",
        qty: 0,
        price: 700,
        image_url: "./suit.png",
      },
      {
        id: "5",
        name: "Kaftan",
        qty: 0,
        price: 250,
        image_url: "./Kaftan.jpg",
      },
      {
        id: "6",
        name: "White Kaftan",
        qty: 0,
        price: 300,
        image_url: "./w-kaftan.jpg",
      },
      {
        id: "7",
        name: "Shirt",
        qty: 0,
        price: 100,
        image_url: "./shirts.jpg",
      },
      {
        id: "8",
        name: "White Shirt",
        qty: 0,
        price: 100,
        image_url: "./w-shirts.webp",
      },
      {
        id: "9",
        name: "Sweater",
        qty: 0,
        price: 100,
        image_url: "./sweater.jpg",
      },
      {
        id: "10",
        name: "Jacket",
        qty: 0,
        price: 200,
        image_url: "./jacket.webp",
      },
      {
        id: "11",
        name: "White Gown",
        qty: 0,
        price: 250,
        image_url: "./gown.webp",
      },
      {
        id: "12",
        name: "Gown",
        qty: 0,
        price: 200,
        image_url: "./gown.webp",
      },
      {
        id: "13",
        name: "Shirt",
        qty: 0,
        price: 100,
        image_url: "./shirts.jpg",
      },
      {
        id: "14",
        name: "Shirt & Blouse",
        qty: 0,
        price: 200,
        image_url: "./skirt&blouse.jpg",
      },
    ];
  } else if (category === "repair") {
    return [
      {
        id: "1",
        name: "White Abgada",
        qty: 0,
        price: 200,
        image_url: "./w-abgada.png",
      },
      {
        id: "2",
        name: "Colored Abgada",
        qty: 0,
        price: 200,
        image_url: "./agbada.png",
      },
      {
        id: "3",
        name: "Suit",
        qty: 0,
        price: 200,
        image_url: "./suit.png",
      },
      {
        id: "4",
        name: "White Suit",
        qty: 0,
        price: 200,
        image_url: "./suit.png",
      },
      {
        id: "5",
        name: "Kaftan",
        qty: 0,
        price: 200,
        image_url: "./Kaftan.jpg",
      },
      {
        id: "6",
        name: "White Kaftan",
        qty: 0,
        price: 200,
        image_url: "./w-kaftan.jpg",
      },
      {
        id: "7",
        name: "Shirt",
        qty: 0,
        price: 200,
        image_url: "./shirts.jpg",
      },
      {
        id: "8",
        name: "White Shirt",
        qty: 0,
        price: 200,
        image_url: "./w-shirts.webp",
      },
      {
        id: "9",
        name: "Sweater",
        qty: 0,
        price: 200,
        image_url: "./sweater.jpg",
      },
      {
        id: "10",
        name: "Jacket",
        qty: 0,
        price: 200,
        image_url: "./jacket.webp",
      },
      {
        id: "11",
        name: "White Gown",
        qty: 0,
        price: 200,
        image_url: "./gown.webp",
      },
      {
        id: "12",
        name: "Gown",
        qty: 0,
        price: 200,
        image_url: "./gown.webp",
      },
      {
        id: "13",
        name: "Shirt",
        qty: 0,
        price: 200,
        image_url: "./shirts.jpg",
      },
      {
        id: "14",
        name: "Shirt & Blouse",
        qty: 0,
        price: 200,
        image_url: "./skirt&blouse.jpg",
      },
      {
        id: "15",
        name: "Small Towel",
        qty: 0,
        price: 200,
        image_url: "./towel.jpg",
      },
      {
        id: "16",
        name: "Big Towel",
        qty: 0,
        price: 200,
        image_url: "./towel.jpg",
      },
      {
        id: "17",
        name: "Small Duvet",
        qty: 0,
        price: 200,
        image_url: "./duviet.webp",
      },
      {
        id: "18",
        name: "Big Duvet",
        qty: 0,
        price: 200,
        image_url: "./duviet.webp",
      },
    ];
  }
};
